language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # Try it out:
  - "pypy"
  - "pypy3"
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - pytest -m unittest --cov=redicts --cov-report term-missing
after_success:
  - coveralls
