language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"
install:
  - pip install -e . --use-mirrors
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - pytest -m unittest --cov=redicts --cov-report term-missing
after_success:
  - coveralls
